server:
  port: 8080
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        format_sql: true
    hibernate:
      ddl-auto: none
    database-platform: com.pible.config.database.CustomPGDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/postgres
  config:
    activate:
      on-profile: local
  jackson:
    property-naming-strategy: SNAKE_CASE
security:
  jwt:
    key: custom_sharing_planner_jwt_secret_key
    minutes: 60
  ignore:
    url: /**
image:
  path: C:\image_test\
